### ISSUE TITLE
Can not send Slack message

### ISSUE THREAD

**Issue by duanvnc** [ogrodnek/code-pipeline-slack#34]
Hi there, 

I have been setup Lambda and Codepipelines successfully and the Cloudwatch Event is working now. The Slack Tokens are work with  #builds channel as well.

However, Lambda function seems not works, I always received an error message like this:

```
list indices must be integers, not str: TypeError
Traceback (most recent call last):
  File "/var/task/notifier.py", line 98, in run
    m = process(event)
  File "/var/task/notifier.py", line 90, in process
    if event['source'] == "aws.codepipeline":
TypeError: list indices must be integers, not str
```

Anyone knows why?

Thank you so much!

**Comment by paulcookie** [comment]
Same stuff

**Comment by paulcookie** [comment]
Looks like it's due this deprecations https://api.slack.com/methods/channels.list
